name:                artiflakery
version:             1.1.0
github:              "JulienMalka/artiflakery"
license:             EUPL-1.2
author:              "Julien Malka"
maintainer:          "julien.malka@me.com"
copyright:           "2025 Julien Malka"

extra-source-files:
- README.md

description:          A webserver for on the fly delivery of Nix flake artifacts 

dependencies:
- base >= 4.7 && < 5
- wai >= 3.2
- warp
- http-types
- async
- containers
- process
- time
- text
- bytestring
- wai-app-static
- wai-websockets
- websockets
- directory
- unix
- filepath
- ansi-terminal
- crypton
- base64-bytestring
- cookie
- co-log
- co-log-core
- exceptions
- bcrypt
- optparse-applicative
- file-embed
- unliftio

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings

executables:
  artiflakery-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - artiflakery


